### PR TITLE
Updated to 0.6.1

### PR DESCRIPTION
**Pull request by pauloxnet**
Aligned to pypi 0.6.0 version
Fix some Python3 compatability issue.

### CODE REVIEW

**Comment by bennylope** [comment]
🐍 👍

**Comment by pauloxnet** [comment]
@bennylope can you please release version 0.6.1 on https://pypi.org/project/django-quagga ?

**Comment by gabbork** [comment]
@bennylope is the new release planned already? Thanks

**Comment by carmelocatalfamo** [comment]
New release would be useful :)

**Comment by drn8** [comment]
Yes it would be great for pip use. Thanks

**Comment by bennylope** [comment]
Wow, I appreciate the enthusiasm! I had to actually sit down to run do the hard work of adding a new tag and typing a single command to issue the release, but I finally found time. It's up on PyPI. Cheers 🍻

**Comment by pauloxnet** [comment]
Thanks for your work, I really appreciate your contributions to the open source world. Cheers 🍻

**Comment by bennylope** [comment]
Also, thanks again for the update, it's a hugehelp. I never bothered updating the AUTHORS file but I'd encourage you to add your name.

**Pull request merged**
